version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'development'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'developer'
    ports:
      - "3306:3306"

  backend:
    image: backend:v1
    restart: always
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - php

  php:
    image: php:v1
    restart: always
    working_dir: /app
    build:
      context: docker/php
    volumes:
      - ./:/app
    depends_on:
      - db

  jenkins:
    image: "jenkins/jenkins:alpine"
    ports:
      - "20300:8080"
    env_file: .env
    environment:
      - APPLICATION_ENV=development
      - DEVELOPMENT_MODE=true
      - SYMFONY_ENV=dev


volumes:
  postgres_data:
